In [1]:
x = [1, 2, 3, 4, 5]

import numpy as np
np.array(x)


array([1, 2, 3, 4, 5])

In [3]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])

x.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
import numpy as np
x = np.array([2.0, 4.0, 6.0])

np.column_stack([np.ones(len(x)), x ])

array([[1., 2.],
       [1., 4.],
       [1., 6.]])

In [ ]:
samples = np.array([0.2, 0.7, 1.1, -0.3, 0.5])
t = 0.5

p = np.mean(samples > t)
print(p)

0.4


In [17]:
x = np.array([-2, 0, 3, -1, 5])

non_negative = np.sum(x >= 0)
print(non_negative)
    

3


In [19]:
n = 400          # number of samples
delta = 0.05     # confidence level (95%)

l = np.sqrt(np.log(2/delta)/(2*n))

In [20]:
metric = 0.78
ci = [metric - l, metric + l]

In [ ]:
z = X @ beta + b0
p = np.exp(z)/(1+np.exp(z))


In [ ]:
y = np.array([...])   # 0/1 labels
p = np.array([...])   # probabilities
eps = 1e-12

loss = -np.mean(y*np.log(p+eps) + (1-y)*np.log(1-p+eps))

In [ ]:
p = np.array([...])   # probabilities
y_hat = (p >= 0.5).astype(int)

In [ ]:
y    = np.array([...])   # true labels (0/1)
yhat = np.array([...])   # predicted labels (0/1)
tp = np.sum((yhat == 1) & (y == 1))

TypeError: unsupported operand type(s) for /: 'ellipsis' and 'ellipsis'

In [ ]:
precision = tp / (tp + fp)

In [ ]:
y    = np.array([...])
yhat = np.array([...])
tp = np.sum((yhat == 1) & (y == 1))
fp = np.sum((yhat == 0) & (y == 1))
fn = np.sum((yhat == 1) & (y == 0))
tn = np.sum((yhat == 0) & (y == 0))
accuracy = (tp + tn) / (tp + fp + fn + tn)

In [ ]:
C = np.array([[2, 1],
              [0, 0]])
